package com.dld.android.pay;

import java.util.ArrayList;

public final class Products {
    ArrayList<ProductDetail> mproductlist = new ArrayList();

    public ArrayList<ProductDetail> retrieveProductInfo() {
        ProductDetail localProductDetail = new ProductDetail();
        localProductDetail.subject = "123456";
        localProductDetail.body = "2010新款NIKE 耐克902第三代板鞋 耐克男女鞋 386201 白红";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "魅力香水";
        localProductDetail.body = "新年特惠 adidas 阿迪达斯走珠 香体止汗走珠 多种香型可选";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "珍珠项链";
        localProductDetail.body = "【2元包邮】韩版 韩国 流行饰品太阳花小巧雏菊 珍珠项链2M15";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "三星 原装移动硬盘";
        localProductDetail.body = "三星 原装移动硬盘 S2 320G 带加密 三星S2 韩国原装 全国联保";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "发箍发带";
        localProductDetail.body = "【肉来来】超热卖 百变小领巾 兔耳朵布艺发箍发带";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "台版N97I";
        localProductDetail.body = "台版N97I 有迷你版 双卡双待手机 挂QQ JAVA 炒股 来电归属地 同款比价 ";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "苹果手机";
        localProductDetail.body = "山寨国产红苹果手机 Hiphone I9 JAVA QQ后台 飞信 炒股 UC";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "蝴蝶结";
        localProductDetail.body = "【饰品实物拍摄】满30包邮 三层绸缎粉色 蝴蝶结公主发箍多色入";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "韩版雪纺";
        localProductDetail.body = "饰品批发价 韩版雪纺纱圆点布花朵 山茶玫瑰花 发圈胸针两用 6002";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "五皇纸箱";
        localProductDetail.body = "加固纸箱 会员包快递拍好去运费冲纸箱首个五皇";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "MF唱片";
        localProductDetail.body = "【正版】MF唱片 HIFI毒药4 毒药涅磐再造 海洛 因新4号HD天碟1CD";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "学习机";
        localProductDetail.body = "六人行老友记friends全10季英语学习机版 MP3版子精读笔记";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "联华卡";
        localProductDetail.body = "联华OK卡，特价供应联华卡，联华OK卡，积点卡982折 卡密或代充";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "粽子批发";
        localProductDetail.body = "嘉兴粽子批发团购真真老老之大肉粽";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "话费充值";
        localProductDetail.body = "【四钻信誉】北京移动30元 电脑全自动充值 1到10分钟内到账";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "短袖T恤";
        localProductDetail.body = "爱马仕男装短袖T恤2010新款时尚夏装韩版男士T恤正品原单圆领修身";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "田园沙发";
        localProductDetail.body = "环保 韩式田园沙发/布艺沙发/现代沙发/特价田园沙发<可定做>";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "夏季登山鞋";
        localProductDetail.body = "8071男女士专柜正品夏季户外防滑鞋户外鞋登山鞋徒步鞋防水透气灰";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "精品娃娃";
        localProductDetail.body = "宜家宜精品娃娃，超柔短毛绒海豚抱枕 75厘米 全国包邮";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        localProductDetail = new ProductDetail();
        localProductDetail.subject = "HTC G5 谷歌G5";
        localProductDetail.body = "HTC G5 谷歌G5 Google G5 先验货后付款 支票刷卡 易人在线";
        localProductDetail.price = "一口价:0.01";
        localProductDetail.resId = 30;
        this.mproductlist.add(localProductDetail);
        return this.mproductlist;
    }

    public class ProductDetail {
        String body;
        String price;
        int resId;
        String subject;

        public ProductDetail() {
        }
    }
}
